package earth.cube.tools.file_backup.model.test_files;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;

import earth.cube.tools.file_backup.model.AbstractLinuxTestFile;
import earth.cube.tools.file_backup.model.LinuxFile;

/** File generated by an Action class like 'purged.txt'.
 * 
 * @author joerg
 *
 */
public class GeneratedFile extends AbstractLinuxTestFile {

	public GeneratedFile(String sLogicalName) throws IOException {
		super(sLogicalName, (byte[]) null);
		setDate(null);
	}
	
	public boolean isGenerated() {
		return true;
	}
	
	public void create(File file) throws IOException, SQLException {
		if(_file != null)
			throw new IllegalStateException("already used!");
		
		_file = file;
	}
	
	public AbstractLinuxTestFile copy() {
		try {
			return new GeneratedFile(_sLogicalName);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}	

	
	public void verify() throws IOException, SQLException {
		LinuxFile linuxFile = getLinuxFile();
		
		assertFalse(linuxFile.isDirectory());
		assertTrue(linuxFile.isFile());
	
		assertTrue(linuxFile.getInode().getSize() > 0);
	}	
	
}
