package earth.cube.tools.file_backup.commons;

public enum ValidationError {
	CHANGED_TIME, SIZE, EXTENSION, SHA256, SHA256_SOURCE, SHA256_UPDATED, DUMMY, MISSING_FILES, UNEXPECTED_INODE_DB_ENTRY, EXPECTED_FILE_INVALID, EXPECTED_FILE_VALID, CHANGED_TIME_OLDER, CHANGED_TIME_NEWER, MISSING_DB_FILE_ENTRY, MODIFICATION_TIME_OLDER, MODIFICATION_TIME_NEWER

}
